export const DATE_CONSTANTS = {
  MIN_WEEKS: 1,
  MAX_WEEKS: 52,
  DAYS_PER_WEEK: 7,
  DAYS_IN_YEAR: 365,
  MIN_DURATION_DAYS: 7,
} as const;

export const TIME_CONSTANTS = {
  MILLISECONDS_PER_DAY: 86400000,
  HOURS_PER_DAY: 24,
  MINUTES_PER_HOUR: 60,
  DAYS_PER_WEEK: 7,
} as const;

export const WEEK_CONSTANTS = {
  DAYS_PER_WEEK: 7,
  WEEK_START_DAY_OFFSET: 0,
  WEEK_END_DAY_OFFSET: 6,
  MIN_CYCLE_DURATION_DAYS: 7,
  MAX_CYCLE_DURATION_DAYS: 365,
  MILLISECONDS_PER_DAY: 86400000,
} as const;