export const WEEK_CONSTANTS = {
  DAYS_PER_WEEK: 7,
  WEEK_START_DAY_OFFSET: 0,
  WEEK_END_DAY_OFFSET: 6,
  MIN_CYCLE_DURATION_DAYS: 7,
  MAX_CYCLE_DURATION_DAYS: 365,
  MILLISECONDS_PER_DAY: 86400000,
} as const;